################################################################################
#                   Various predbat sensors                                    #
#                       Made By Johan71                                        #
################################################################################
sensor:
  - platform: template
    sensors:
      pv_power:
        friendly_name: "PV Power kW"
        unit_of_measurement: "kW"
        unique_id: "pv_power"
        value_template: >
          {% set sensor_value = states('sensor.inverter_input_power') %}
          {% if sensor_value not in ['unknown', 'unavailable', 'none'] %}
            {{ sensor_value | float(0) / 1000 }}
          {% else %}
            0
          {% endif %}
          
      pv_today2:
        friendly_name: "PV Today kWh"
        unit_of_measurement: "kWh"
        value_template: >
          {% set sensor_value = states('sensor.inverter_daily_yield') %}
          {% if sensor_value not in ['unknown', 'unavailable', 'none'] %}
          {{ sensor_value | float(0) }}
          {% else %}
           0
          {% endif %}

      ev_today_kwh:
        friendly_name: "EV Today kWh"
        unit_of_measurement: "kWh"
        unique_id: "ev_today_kwh"
        value_template: >
          {% set sensor_value = states('sensor.go_echarger_265216_wh') %}
          {% if sensor_value not in ['unknown', 'unavailable', 'none'] %}
            {{ sensor_value | float(0) / 1000 }}
          {% else %}
            0
          {% endif %}

      go_echarger_kwh:
        friendly_name: "Go-eCharger Energy kWh"
        unit_of_measurement: "kWh"
        unique_id: "go_echarger_kwh"
        value_template: >
          {% set eto = states('sensor.go_echarger_265216_eto') %}
          {% if eto not in ['unknown', 'unavailable', 'none'] %}
            {{ eto | float(0) / 1000 }}
          {% else %}
            0
          {% endif %}

      battery_capacity_kw:
        friendly_name: "Battery State of Capacity in kW"
        unit_of_measurement: "kW"
        unique_id: "battery_capacity_kw"
        value_template: >
          {% set max_capacity_kw = 10 %}
          {% set soc = states('sensor.battery_state_of_capacity') %}
          {% if soc not in ['unknown', 'unavailable', 'none'] %}
            {{ (max_capacity_kw * soc | float(0) / 100) | round(2) }}
          {% else %}
            0
          {% endif %}

##############################################################################
## Integration sensors (power → energy)
##############################################################################

  - platform: integration
    source: sensor.house_consumption_power
    name: "House Consumption - Energy"
    unit_prefix: k
    round: 2
    unique_id: "house_consumption_energy"

  - platform: integration
    source: sensor.battery_to_house
    name: "Battery to House Energy"
    unit_prefix: k
    round: 2
    unique_id: "battery_to_house_energy"

##############################################################################
## Utility meters - Daily energy tracking
##############################################################################

utility_meter:
  import_today:
    source: sensor.power_meter_consumption
    cycle: daily
    unique_id: "import_today"

  export_today:
    source: sensor.power_meter_exported
    cycle: daily
    unique_id: "export_today"

  pv_today:
    source: sensor.solar_energy_riemann
    cycle: daily
    unique_id: "pv_today"

  load_today:
    source: sensor.house_consumption_energy
    cycle: daily
    unique_id: "load_today"

  ev_today:
    source: sensor.go_echarger_265216_wh
    cycle: daily
    unique_id: "ev_today"
##############################################################################
## Input text
##############################################################################
    
input_text:
  huawei_capacity_charge_periods:
    name: Huawei capacity charge periods
    max: 255
  huawei_capacity_export_periods:
    name: Huawei capacity export periods
    max: 255
###############################################################################
##     END
###############################################################################
